### ISSUE TITLE
Expectation of becoming a W3C standard

### ISSUE THREAD

**Issue by CThuleHansen** [openprov/prov-jsonld#1]
Hi,
Thanks for creating this interesting work.
Is there an expectation of becoming a w3c standard or even an expected date?

Thank you

**Comment by lucmoreau** [comment]
Thank you for your interest. I am ironing out a few issues, and intend to make it a member submission.

Ideally before mid- July.

Kind regards,





Luc Moreau
________________________________
From: Casper Thule ***@***.***>
Sent: Monday, June 17, 2024 9:54:45 PM
To: openprov/prov-jsonld ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openprov/prov-jsonld] Expectation of becoming a W3C standard (Issue #1)


Hi,
Thanks for creating this interesting work.
Is there an expectation of becoming a w3c standard or even an expected date?

Thank you

**Comment by CThuleHansen** [comment]
Thank you
